### ISSUE TITLE
"Okundu" Olarak İşaretleme Özelliği

### ISSUE THREAD

**Issue by mytunca** [Yusuf-YENICERI/Hatim-Dagit#19]
Hocam alınmayan cüzler gri, alınanlar sarı, okunanlar yeşil renk olabilir.

**Comment by Yusuf-YENICERI** [comment]
Tavsiye için Allah razı olsun. Bu özelliği isteyen bir çok kişi mevcut, hatim oluşturulması sırasında bir seçenek olarak sunulabilir inşaAllah

**Comment by Yusuf-YENICERI** [comment]
@mytunca yıllar sonra da olsa eklendi inşallah.
😂
